version: '2'
services:
  app:
    volumes:
      - .:/cmp
    command: python manage.py runserver 0.0.0.0:${DOCKER_EXPOSED_PORT}
    environment:
      - DEFAULT_DEBUG_EMAIL_URL=smtp://mailcatcher:25/
    links:
      - mailcatcher
  gulp:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/cmp
    command: gulp watch
  mailcatcher:
    image: tophfr/mailcatcher:latest
    ports:
      - 1080:80