# Generated by Django 2.0b1 on 2017-11-06 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='teams',
        ),
        migrations.AddField(
            model_name='purchase',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Team'),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('granted', 'Granted'), ('denied', 'Denied'), ('waitlisted', 'Wait-listed'), ('relinquished', 'Relinquished')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_types', to='marketplace.Product'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
