# Generated by Django 2.0b1 on 2017-11-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_licenserequest_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
