# Generated by Django 2.0b1 on 2017-11-08 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20171107_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenserequest',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AlterField(
            model_name='usermarketplaceinfo',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='marketplace.Team'),
        ),
        migrations.AlterField(
            model_name='usermarketplaceinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to=settings.AUTH_USER_MODEL),
        ),
    ]
